In [57]:
addprocs(2)

2-element Array{Int64,1}:
 2
 3

In [92]:
Nlist = repmat([1000],10)
@everywhere myfun(N,M) = sum(randn(N,N)^2)
@everywhere M = 1000
@time pmap(N -> myfun(N,M),Nlist)

10-element Array{Any,1}:
   9718.16
   1942.9 
 -20147.1 
  -6331.67
 -58415.4 
   3735.29
  27210.0 
  13618.2 
 -10564.7 
  31347.8 

1.552528 seconds (2.58 k allocations: 170.928 KB)


In [116]:
s = "holy2a[18301,18301-18302]"
idx = searchindex(s,"[")
num_digits = length(split(split(s[idx+1:end-1],",")[end],"-")[end])

5

In [98]:
split(split(s[idx+1:end-1],",")[end],"-")

1-element Array{SubString{ASCIIString},1}:
 "18302"

In [104]:
n = 100
length("$n")

3

In [105]:
"0"^3

"000"

In [109]:
function pad_zeros(n::Int,num_digits::Int)
	num_already = length("$n")
	num_needed = num_digits - num_already
	if num_needed < 0 num_needed = 0 end
	return "0"^num_needed * "$n"
end


pad_zeros (generic function with 1 method)

In [114]:
pad_zeros(4,-2)

"4"